import { Content } from "@/types";

export const animes: Content[] = [
  {
    id: "a-1",
    title: "Attack on Titan",
    description:
      "Depois que sua cidade natal é destruída e sua mãe é morta, o jovem Eren Jaeger jura limpar a terra dos Titãs humanóides gigantes.",
    thumbnailUrl: "/png/attack on titan.jpg",
    coverUrl: "/png/attack on titan.jpg",
    genre: ["Ação", "Fantasia"],
    rating: 4.9,
    year: 2013,
    ageRating: "16",
    type: "anime",
    seasons: 4,
    videoUrl: "https://www.youtube.com/embed/MGRm4IzK1SQ",
  },
  {
    id: "a-2",
    title: "Demon Slayer",
    description:
      "Uma família é atacada por demônios e apenas dois membros sobrevivem - Tanjiro e sua irmã Nezuko, que está se transformando em um demônio.",
    thumbnailUrl: "/png/demon slayer.webp",
    coverUrl: "/png/demon slayer.webp",
    genre: ["Ação", "Fantasia"],
    rating: 4.8,
    year: 2019,
    ageRating: "14",
    type: "anime",
    seasons: 3,
    videoUrl: "https://www.youtube.com/embed/VQGCKyvzIM4",
  },
  {
    id: "a-3",
    title: "One Piece",
    description:
      "Monkey D. Luffy navega com sua tripulação de piratas em busca do maior tesouro do mundo, conhecido como 'One Piece'.",
    thumbnailUrl: "/png/one piece.jpg",
    coverUrl: "/png/one piece.jpg",
    genre: ["Aventura", "Ação"],
    rating: 4.9,
    year: 1999,
    ageRating: "12",
    type: "anime",
    seasons: 20,
    videoUrl: "https://www.youtube.com/embed/S8_YwFLCh4U",
  },
  {
    id: "a-4",
    title: "Jujutsu Kaisen",
    description:
      "Yuji Itadori entra em uma escola de feiticeiros após engolir um objeto amaldiçoado extremamente poderoso.",
    thumbnailUrl: "/png/jujutsu-kaisen.png",
    coverUrl: "/png/jujutsu-kaisen.png",
    genre: ["Ação", "Sobrenatural"],
    rating: 4.7,
    year: 2020,
    ageRating: "14",
    type: "anime",
    seasons: 2,
    videoUrl: "https://www.youtube.com/embed/f7R6NA4Yo00",
  },
  {
    id: "a-5",
    title: "My Hero Academia",
    description:
      "Em um mundo onde quase todos possuem poderes, um garoto sem habilidades sonha em ser herói.",
    thumbnailUrl: "/png/my hero academia.jpg",
    coverUrl: "/png/my hero academia.jpg",
    genre: ["Ação", "Super-herói"],
    rating: 4.5,
    year: 2016,
    ageRating: "12",
    type: "anime",
    seasons: 6,
    videoUrl: "https://www.youtube.com/embed/wIb3nnOeves",
  },
  {
    id: "a-6",
    title: "Fullmetal Alchemist: Brotherhood",
    description:
      "Dois irmãos alquimistas buscam a Pedra Filosofal após uma tentativa de transmutação humana dar terrivelmente errado.",
    thumbnailUrl: "/png/fullmetal alchemist.jpg",
    coverUrl: "/png/fullmetal alchemist.jpg",
    genre: ["Aventura", "Fantasia"],
    rating: 5.0,
    year: 2009,
    ageRating: "14",
    type: "anime",
    seasons: 1,
    videoUrl: "https://www.youtube.com/embed/7H9v210uH40",
  },
  {
    id: "a-7",
    title: "Chainsaw Man",
    description:
      "Denji faz um pacto com seu demônio-serra elétrica para sobreviver como caçador de demônios.",
    thumbnailUrl: "/png/chainsaw-man.jpg",
    coverUrl: "/png/chainsaw-man.jpg",
    genre: ["Ação", "Terror"],
    rating: 4.6,
    year: 2022,
    ageRating: "18",
    type: "anime",
    seasons: 1,
    videoUrl: "https://www.youtube.com/embed/dFlDRhvM4L0",
  },
  {
    id: "a-8",
    title: "Haikyuu!!",
    description:
      "Hinata sonha em se tornar uma lenda do voleibol mesmo com sua baixa estatura.",
    thumbnailUrl: "/png/haikyuu.jpg",
    coverUrl: "/png/haikyuu.jpg",
    genre: ["Esporte", "Comédia"],
    rating: 4.7,
    year: 2014,
    ageRating: "10",
    type: "anime",
    seasons: 4,
    videoUrl: "https://www.youtube.com/embed/JOGp2c7-cKc",
  },
  {
    id: "a-9",
    title: "Spy x Family",
    description:
      "Um espião precisa formar uma família falsa para cumprir uma missão, sem saber que sua esposa é assassina e sua filha é telepata.",
    thumbnailUrl: "/png/spy-x-family.jpg",
    coverUrl: "/png/spy-x-family.jpg",
    genre: ["Comédia", "Ação"],
    rating: 4.8,
    year: 2022,
    ageRating: "12",
    type: "anime",
    seasons: 2,
    videoUrl: "https://www.youtube.com/embed/CCXLUQzuigw",
  },
  {
    id: "a-10",
    title: "Naruto Shippuden",
    description:
      "Naruto retorna à Vila da Folha mais forte do que nunca para enfrentar novas ameaças.",
    thumbnailUrl: "/png/naruto-shippuden.jpg",
    coverUrl: "/png/naruto-shippuden.jpg",
    genre: ["Ação", "Aventura"],
    rating: 4.7,
    year: 2007,
    ageRating: "12",
    type: "anime",
    seasons: 21,
    videoUrl: "https://www.youtube.com/embed/qyYHShF1nZQ",
  },
];
