import { Content } from "@/types";

export const movies: Content[] = [
  {
    id: "m-1",
    title: "Duna: Parte Dois",
    description:
      "Paul Atreides se une a Chani e aos Fremen enquanto busca vingança contra os conspiradores que destruíram sua família.",
    thumbnailUrl: "/png/duna parte2.png",
    coverUrl: "/png/duna parte2.png",
    genre: ["Sci-Fi", "Aventura"],
    rating: 4.9,
    year: 2024,
    ageRating: "14",
    type: "movie",
    duration: "2h 46m",
    videoUrl: "https://www.youtube.com/embed/Way9Dexny3w",
  },
  {
    id: "m-2",
    title: "Oppenheimer",
    description:
      "A história do cientista americano J. Robert Oppenheimer e seu papel no desenvolvimento da bomba atômica.",
    thumbnailUrl: "/png/Oppenheimer-Christopher-Nolan.jpg",
    coverUrl: "/png/Oppenheimer-Christopher-Nolan.jpg",
    genre: ["Biografia", "Drama"],
    rating: 4.8,
    year: 2023,
    ageRating: "14",
    type: "movie",
    duration: "3h",
    videoUrl: "https://www.youtube.com/embed/uYPbbksJxIg",
  },
  {
    id: "m-3",
    title: "Interestelar",
    description:
      "Uma equipe de exploradores viaja através de um buraco de minhoca no espaço na tentativa de garantir a sobrevivência da humanidade.",
    thumbnailUrl: "/png/interstellar.jpg",
    coverUrl: "/png/interstellar.jpg",
    genre: ["Sci-Fi", "Drama"],
    rating: 4.9,
    year: 2014,
    ageRating: "12",
    type: "movie",
    duration: "2h 49m",
    videoUrl: "https://www.youtube.com/embed/zSWdZVtXT7E",
  },
  {
    id: "m-4",
    title: "Blade Runner 2049",
    description:
      "Um novo blade runner descobre um segredo enterrado há muito tempo que tem o potencial de mergulhar o que resta da sociedade no caos.",
    thumbnailUrl: "/png/blade runner 2049.jpg",
    coverUrl: "/png/blade runner 2049.jpg",
    genre: ["Sci-Fi", "Suspense"],
    rating: 4.7,
    year: 2017,
    ageRating: "14",
    type: "movie",
    duration: "2h 44m",
    videoUrl: "https://www.youtube.com/embed/gCcx85zbxz4",
  },
  {
    id: "m-5",
    title: "Matrix",
    description:
      "Um hacker descobre a verdade sobre sua realidade e seu papel na guerra contra os controladores dela.",
    thumbnailUrl: "/png/matrix.jpg",
    coverUrl: "/png/matrix.jpg",
    genre: ["Sci-Fi", "Ação"],
    rating: 4.9,
    year: 1999,
    ageRating: "14",
    type: "movie",
    duration: "2h 16m",
    videoUrl: "https://www.youtube.com/embed/m8e-FF8MsqU",
  },
  {
    id: "m-6",
    title: "John Wick 4: Baba Yaga",
    description:
      "John Wick descobre um caminho para derrotar a Alta Cúpula. Mas antes que ele possa ganhar sua liberdade, Sr. Wick deve enfrentar um novo inimigo.",
    thumbnailUrl: "/png/john-wick-4.jpg",
    coverUrl: "/png/john-wick-4.jpg",
    videoUrl: "https://www.youtube.com/embed/qEVUtrk8_B4",
    duration: "2h 49m",
    genre: ["Ação"],
    year: 2023,
    type: "movie",
    rating: 4.8,
    ageRating: "16",
    cast: ["Keanu Reeves", "Donnie Yen", "Bill Skarsgård"],
    director: "Chad Stahelski",
  },
  {
    id: "m-7",
    title: "Homem-Aranha: Através do Aranhaverso",
    description:
      "Miles Morales é catapultado através do Multiverso, onde ele encontra uma equipe de Pessoas-Aranha encarregada de proteger sua própria existência.",
    thumbnailUrl: "/png/aranha verso.png",
    coverUrl: "/png/aranha verso.png",
    videoUrl: "https://www.youtube.com/embed/shW9i6k8cB0",
    duration: "2h 20m",
    genre: ["Animação", "Ação", "Aventura"],
    year: 2023,
    type: "movie",
    ageRating: "10",
    rating: 4.9,
    cast: ["Shameik Moore", "Hailee Steinfeld", "Brian Tyree Henry"],
    director: "Joaquim Dos Santos",
  },
  {
    id: "m-8",
    title: "Mad Max: Estrada da Fúria",
    description:
      "Em um deserto pós-apocalíptico, Max se une à Imperatriz Furiosa em uma fuga explosiva de um tirano brutal.",
    thumbnailUrl: "/png/mad max  estrada da furia.jpg",
    coverUrl: "/png/mad max  estrada da furia.jpg",
    genre: ["Ação", "Sci-Fi"],
    rating: 4.8,
    year: 2015,
    ageRating: "16",
    type: "movie",
    duration: "2h",
    videoUrl: "https://www.youtube.com/embed/hEJnMQG9ev8",
  },
  {
    id: "m-9",
    title: "Gladiador",
    description:
      "Um general romano é traído e sua família é assassinada. Ele retorna a Roma como gladiador em busca de vingança.",
    thumbnailUrl: "/png/gladiator.webp",
    coverUrl: "/png/gladiator.webp",
    genre: ["Ação", "Drama"],
    rating: 4.8,
    year: 2000,
    ageRating: "16",
    type: "movie",
    duration: "2h 35m",
    videoUrl: "https://www.youtube.com/embed/owK1qxDselE",
  },
  {
    id: "m-10",
    title: "O Cavaleiro das Trevas",
    description:
      "Batman enfrenta o Coringa, um criminoso caótico que planeja mergulhar Gotham City na anarquia.",
    thumbnailUrl: "/png/o cavaleiro das trevas.jpg",
    coverUrl: "/png/o cavaleiro das trevas.jpg",
    genre: ["Ação", "Crime"],
    rating: 5.0,
    year: 2008,
    ageRating: "14",
    type: "movie",
    duration: "2h 32m",
    videoUrl: "https://www.youtube.com/embed/EXeTwQWrcwY",
  },
  {
    id: "m-11",
    title: "Vingadores: Guerra Infinita",
    description:
      "Os Vingadores unem forças para impedir Thanos de reunir as Joias do Infinito e destruir metade do universo.",
    thumbnailUrl: "/png/vingadores guerra infinita.png",
    coverUrl: "/png/vingadores guerra infinita.png",
    genre: ["Ação", "Fantasia"],
    rating: 4.7,
    year: 2018,
    ageRating: "12",
    type: "movie",
    duration: "2h 29m",
    videoUrl: "https://www.youtube.com/embed/6ZfuNTqbHE8",
  },
  {
    id: "m-12",
    title: "Pantera Negra",
    description:
      "T'Challa retorna a Wakanda para assumir o trono, mas precisa enfrentar um antigo inimigo com planos para o mundo.",
    thumbnailUrl: "/png/pantera negra.webp",
    coverUrl: "/png/pantera negra.webp",
    genre: ["Ação", "Super-herói"],
    rating: 4.6,
    year: 2018,
    ageRating: "12",
    type: "movie",
    duration: "2h 14m",
    videoUrl: "https://www.youtube.com/embed/xjDjIWPwcPU",
  },
  {
    id: "m-13",
    title: "O Senhor dos Anéis: A Sociedade do Anel",
    description:
      "Um jovem hobbit embarca em uma jornada épica para destruir um anel poderoso e maligno.",
    thumbnailUrl: "/png/senhor dos aneis sociedade do anel.png",
    coverUrl: "/png/senhor dos aneis sociedade do anel.png",
    genre: ["Fantasia", "Aventura"],
    rating: 5.0,
    year: 2001,
    ageRating: "12",
    type: "movie",
    duration: "2h 58m",
    videoUrl: "https://www.youtube.com/embed/V75dMMIW2B4",
  },
  {
    id: "m-14",
    title: "O Senhor dos Anéis: As Duas Torres",
    description:
      "A Sociedade se separa, mas continua a luta contra as forças de Sauron enquanto Frodo segue rumo a Mordor.",
    thumbnailUrl: "/png/senhor dos aneis as duas torres.jpg",
    coverUrl: "/png/senhor dos aneis as duas torres.jpg",
    genre: ["Fantasia", "Aventura"],
    rating: 4.9,
    year: 2002,
    ageRating: "12",
    type: "movie",
    duration: "2h 59m",
    videoUrl: "https://www.youtube.com/embed/LbfMDwc4azU",
  },
  {
    id: "m-15",
    title: "O Senhor dos Anéis: O Retorno do Rei",
    description:
      "As forças de Gondor e Rohan se preparam para a batalha final enquanto Frodo e Sam se aproximam de Mordor.",
    thumbnailUrl: "/png/senhor dos aneis o retorno do rei.jpg",
    coverUrl: "/png/senhor dos aneis o retorno do rei.jpg",
    genre: ["Fantasia", "Aventura"],
    rating: 5.0,
    year: 2003,
    ageRating: "12",
    type: "movie",
    duration: "3h 21m",
    videoUrl: "https://www.youtube.com/embed/r5X-hFf6Bwo",
  },
  {
    id: "m-16",
    title: "A Origem",
    description:
      "Um ladrão que invade sonhos recebe a tarefa impossível de implantar uma ideia na mente de um alvo.",
    thumbnailUrl: "/png/a origem.jpg",
    coverUrl: "/png/a origem.jpg",
    genre: ["Sci-Fi", "Suspense"],
    rating: 4.8,
    year: 2010,
    ageRating: "14",
    type: "movie",
    duration: "2h 28m",
    videoUrl: "https://www.youtube.com/embed/YoHD9XEInc0",
  },
  {
    id: "m-17",
    title: "Clube da Luta",
    description:
      "Um homem insatisfeito com a vida corporativa conhece um vendedor de sabão e juntos formam um clube secreto de luta.",
    thumbnailUrl: "/png/clube da luta.webp",
    coverUrl: "/png/clube da luta.webp",
    genre: ["Drama", "Suspense"],
    rating: 4.7,
    year: 1999,
    ageRating: "18",
    type: "movie",
    duration: "2h 19m",
    videoUrl: "https://www.youtube.com/embed/SUXWAEX2jlg",
  },
  {
    id: "m-18",
    title: "Forrest Gump",
    description:
      "Através dos olhos de Forrest, vemos momentos marcantes da história americana enquanto ele busca seu grande amor.",
    thumbnailUrl: "/png/forrest gump.jpg",
    coverUrl: "/png/forrest gump.jpg",
    genre: ["Drama", "Romance"],
    rating: 4.9,
    year: 1994,
    ageRating: "12",
    type: "movie",
    duration: "2h 22m",
    videoUrl: "https://www.youtube.com/embed/bLvqoHBptjg",
  },
  {
    id: "m-19",
    title: "Pulp Fiction: Tempo de Violência",
    description:
      "Histórias interligadas de criminosos, boxeadores e um casal de assaltantes se desenrolam em Los Angeles.",
    thumbnailUrl: "/png/pulp fiction tempo de violencia.jpg",
    coverUrl: "/png/pulp fiction tempo de violencia.jpg",
    genre: ["Crime", "Drama"],
    rating: 4.8,
    year: 1994,
    ageRating: "18",
    type: "movie",
    duration: "2h 34m",
    videoUrl: "https://www.youtube.com/embed/s7EdQ4FqbhY",
  },
  {
    id: "m-20",
    title: "Coringa",
    description:
      "Um comediante fracassado em Gotham City mergulha na loucura e se transforma em um dos maiores vilões do crime.",
    thumbnailUrl: "/png/coringa.jpg",
    coverUrl: "/png/coringa.jpg",
    genre: ["Drama", "Suspense"],
    rating: 4.7,
    year: 2019,
    ageRating: "16",
    type: "movie",
    duration: "2h 2m",
    videoUrl: "https://www.youtube.com/embed/zAGVQLHvwOY",
  },
  {
    id: "m-21",
    title: "Parasita",
    description:
      "Uma família pobre se infiltra na vida de uma família rica, desencadeando uma série de eventos imprevisíveis.",
    thumbnailUrl: "/png/parasita.webp",
    coverUrl: "/png/parasita.webp",
    genre: ["Drama", "Suspense"],
    rating: 4.9,
    year: 2019,
    ageRating: "16",
    type: "movie",
    duration: "2h 12m",
    videoUrl: "https://www.youtube.com/embed/5xH0HfJHsaY",
  },
  {
    id: "m-22",
    title: "Whiplash: Em Busca da Perfeição",
    description:
      "Um jovem baterista de jazz enfrenta um professor abusivo em busca da perfeição musical.",
    thumbnailUrl: "/png/whiplash em busca da perfeição.jpg",
    coverUrl: "/png/whiplash em busca da perfeição.jpg",
    genre: ["Drama", "Música"],
    rating: 4.8,
    year: 2014,
    ageRating: "14",
    type: "movie",
    duration: "1h 47m",
    videoUrl: "https://www.youtube.com/embed/7d_jQycdQGo",
  },
  {
    id: "m-23",
    title: "La La Land: Cantando Estações",
    description:
      "Um músico de jazz e uma aspirante a atriz se apaixonam em Los Angeles enquanto perseguem seus sonhos.",
    thumbnailUrl: "/png/La_La_Land.png",
    coverUrl: "/png/La_La_Land.png",
    genre: ["Romance", "Música"],
    rating: 4.6,
    year: 2016,
    ageRating: "12",
    type: "movie",
    duration: "2h 8m",
    videoUrl: "https://www.youtube.com/embed/0pdqf4P9MB8",
  },
  {
    id: "m-24",
    title: "Homem de Ferro",
    description:
      "Depois de ser sequestrado, o industrial Tony Stark constrói uma armadura de alta tecnologia e se torna o herói Homem de Ferro.",
    thumbnailUrl: "/png/homem de ferro.jpg",
    coverUrl: "/png/homem de ferro.jpg",
    genre: ["Ação", "Super-herói"],
    rating: 4.5,
    year: 2008,
    ageRating: "12",
    type: "movie",
    duration: "2h 6m",
    videoUrl: "https://www.youtube.com/embed/8hYlB38asDY",
  },
  {
    id: "m-25",
    title: "Interestelar 2: Nova Fronteira",
    description:
      "Décadas após a missão original, uma nova equipe viaja além da galáxia em busca de um novo lar para a humanidade.",
    thumbnailUrl: "/png/interstellar 2.jpg",
    coverUrl: "/png/interstellar 2.jpg",
    genre: ["Sci-Fi", "Drama"],
    rating: 4.6,
    year: 2030,
    ageRating: "12",
    type: "movie",
    duration: "2h 45m",
  },
  {
    id: "m-26",
    title: "O Protetor",
    description:
      "Um ex-agente da CIA tenta viver em paz, mas volta à ação para proteger pessoas inocentes.",
    thumbnailUrl: "/png/o-protetor.jpg",
    coverUrl: "/png/o-protetor.jpg",
    genre: ["Ação", "Suspense"],
    rating: 4.3,
    year: 2014,
    ageRating: "16",
    type: "movie",
    duration: "2h 12m",
    videoUrl: "https://www.youtube.com/embed/UV0Nq3gjV44",
  },
  {
    id: "m-27",
    title: "Velozes & Furiosos 7",
    description:
      "A equipe de Dom enfrenta um assassino treinado em busca de vingança pela morte de seu irmão.",
    thumbnailUrl: "/png/velozes-e-furiosos-7.jpg",
    coverUrl: "/png/velozes-e-furiosos-7.jpg",
    genre: ["Ação"],
    rating: 4.2,
    year: 2015,
    ageRating: "14",
    type: "movie",
    duration: "2h 17m",
    videoUrl: "https://www.youtube.com/embed/Skpu5HaVkOc",
  },
  {
    id: "m-28",
    title: "Divertida Mente",
    description:
      "As emoções de uma garota de 11 anos ganham vida e precisam trabalhar juntas quando a família se muda de cidade.",
    thumbnailUrl: "/png/divertida-mente.jpg",
    coverUrl: "/png/divertida-mente.jpg",
    genre: ["Animação", "Família"],
    rating: 4.7,
    year: 2015,
    ageRating: "10",
    type: "movie",
    duration: "1h 42m",
    videoUrl: "https://www.youtube.com/embed/yRUAzGQ3nSY",
  },
  {
    id: "m-29",
    title: "Titanic",
    description:
      "Um artista pobre e uma jovem rica se apaixonam a bordo do infame navio Titanic.",
    thumbnailUrl: "/png/titanic.jpg",
    coverUrl: "/png/titanic.jpg",
    genre: ["Romance", "Drama"],
    rating: 4.8,
    year: 1997,
    ageRating: "12",
    type: "movie",
    duration: "3h 14m",
    videoUrl: "https://www.youtube.com/embed/kVrqfYjkTdQ",
  },
  {
    id: "m-30",
    title: "Toy Story",
    description:
      "Os brinquedos de um garoto ganham vida quando ninguém está olhando e precisam lidar com a chegada de um novo herói espacial.",
    thumbnailUrl: "/png/toy-story.jpg",
    coverUrl: "/png/toy-story.jpg",
    genre: ["Animação", "Família"],
    rating: 4.6,
    year: 1995,
    ageRating: "0",
    type: "movie",
    duration: "1h 21m",
    videoUrl: "https://www.youtube.com/embed/v-PjgYDrg70",
  },
];
