import { Content } from "@/types";

export const series: Content[] = [
  {
    id: "s-1",
    title: "The Last of Us",
    description:
      "Após uma pandemia global destruir a civilização, um sobrevivente endurecido assume o controle de uma garota de 14 anos que pode ser a última esperança da humanidade.",
    thumbnailUrl: "/png/the-last-of-us.jpg",
    coverUrl: "/png/the-last-of-us.jpg",
    genre: ["Drama", "Terror"],
    rating: 4.8,
    year: 2023,
    ageRating: "16",
    type: "series",
    seasons: 1,
    videoUrl: "https://www.youtube.com/embed/uLtkt8BonwM",
  },
  {
    id: "s-2",
    title: "Breaking Bad",
    description:
      "Um professor de química do ensino médio diagnosticado com câncer de pulmão inoperável se volta para a fabricação e venda de metanfetamina.",
    thumbnailUrl: "/png/breaking bad.jpg",
    coverUrl: "/png/breaking bad.jpg",
    genre: ["Crime", "Drama"],
    rating: 5.0,
    year: 2008,
    ageRating: "16",
    type: "series",
    seasons: 5,
    videoUrl: "https://www.youtube.com/embed/HhesaQXLuRY",
  },
  {
    id: "s-3",
    title: "Stranger Things",
    description:
      "Quando um garoto desaparece, sua mãe, um chefe de polícia e seus amigos devem enfrentar forças aterrorizantes para trazê-lo de volta.",
    thumbnailUrl: "/png/stranger things.jpg",
    coverUrl: "/png/stranger things.jpg",
    genre: ["Fantasia", "Terror"],
    rating: 4.7,
    year: 2016,
    ageRating: "14",
    type: "series",
    seasons: 4,
    videoUrl: "https://www.youtube.com/embed/b9EkMc79ZSU",
  },
  {
    id: "s-4",
    title: "Game of Thrones",
    description:
      "Nove famílias nobres lutam pelo controle das terras de Westeros enquanto um antigo inimigo retorna.",
    thumbnailUrl: "/png/game of thrones.jpg",
    coverUrl: "/png/game of thrones.jpg",
    genre: ["Fantasia", "Drama"],
    rating: 4.6,
    year: 2011,
    ageRating: "18",
    type: "series",
    seasons: 8,
    videoUrl: "https://www.youtube.com/embed/KPLWWIOCOOQ",
  },
  {
    id: "s-5",
    title: "Dark",
    description:
      "O desaparecimento de uma criança expõe os segredos e conexões ocultas entre quatro famílias em uma pequena cidade alemã.",
    thumbnailUrl: "/png/Dark_(série).jpg",
    coverUrl: "/png/Dark_(série).jpg",
    genre: ["Sci-Fi", "Mistério"],
    rating: 4.8,
    year: 2017,
    ageRating: "16",
    type: "series",
    seasons: 3,
    videoUrl: "https://www.youtube.com/embed/rrwycJ08PSA",
  },
  {
    id: "s-6",
    title: "Arcane",
    description:
      "Em meio à tensão entre duas cidades, duas irmãs lutam em lados opostos de uma guerra em crescimento.",
    thumbnailUrl: "/png/arcane.jpg",
    coverUrl: "/png/arcane.jpg",
    genre: ["Animação", "Ação"],
    rating: 4.9,
    year: 2021,
    ageRating: "14",
    type: "series",
    seasons: 1,
    videoUrl: "https://www.youtube.com/embed/fXmAurh012s",
  },
  {
    id: "s-7",
    title: "The Boys",
    description:
      "Um grupo de vigilantes decide enfrentar super-heróis corruptos que abusam de seus poderes.",
    thumbnailUrl: "/png/the-boys.jpg",
    coverUrl: "/png/the-boys.jpg",
    genre: ["Ação", "Super-herói"],
    rating: 4.6,
    year: 2019,
    ageRating: "18",
    type: "series",
    seasons: 4,
    videoUrl: "https://www.youtube.com/embed/06rueu_fh30",
  },
  {
    id: "s-8",
    title: "Loki",
    description:
      "Após roubar o Tesseract, Loki é levado perante uma organização que controla as linhas do tempo.",
    thumbnailUrl: "/png/loki.jpg",
    coverUrl: "/png/loki.jpg",
    genre: ["Sci-Fi", "Fantasia"],
    rating: 4.4,
    year: 2021,
    ageRating: "12",
    type: "series",
    seasons: 2,
    videoUrl: "https://www.youtube.com/embed/nW948Va-l10",
  },
  {
    id: "s-9",
    title: "Peaky Blinders",
    description:
      "Uma família de gângsteres na Inglaterra pós-Primeira Guerra Mundial constrói um império criminoso.",
    thumbnailUrl: "/png/peaky-blinders.jpg",
    coverUrl: "/png/peaky-blinders.jpg",
    genre: ["Crime", "Drama"],
    rating: 4.7,
    year: 2013,
    ageRating: "16",
    type: "series",
    seasons: 6,
    videoUrl: "https://www.youtube.com/embed/oVzVdvGIC7U",
  },
  {
    id: "s-10",
    title: "The Witcher",
    description:
      "Um bruxo caçador de monstros enfrenta forças sombrias em um mundo cheio de magia e intrigas políticas.",
    thumbnailUrl: "/png/the-witcher.jpg",
    coverUrl: "/png/the-witcher.jpg",
    genre: ["Fantasia", "Ação"],
    rating: 4.1,
    year: 2019,
    ageRating: "16",
    type: "series",
    seasons: 3,
    videoUrl: "https://www.youtube.com/embed/ndl1W4ltcmg",
  },
];
